from enum import StrEnum


class ErrorCode(StrEnum):
    LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
    EMPTY_LLM_RESPONSE = "EMPTY_LLM_RESPONSE"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
